ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [ com.example.mdmbackend.ApplicationKt.module ]
  }
}

mdm {
  auth {
    sessionTtlMinutes = 43200
  }

  seed {
    adminUser = "admin"
    adminPass = "your_admin_pass"

    deviceUser = "device"
    devicePass = "your_device_pass"

    defaultDeviceUnlockPass = "your_unlock_pass"

    defaultUserCode = "TEST456"
    defaultAllowedApps = ["com.android.settings", "com.android.chrome"]
  }

  db {
    jdbcUrl = "jdbc:mysql://localhost:3306/your_db"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "your_db_user"
    password = "your_db_password"
  }
}