include "application-local-dev.conf"
include "application-integration-test.conf"
include "application-demo.conf"

ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [ com.example.mdmbackend.ApplicationKt.module ]
  }
}

mdm {
  profile = ${?MDM_PROFILE}

  auth {
    sessionTtlMinutes = 43200
  }

  telemetry {
    eventRetentionDays = 30
    usageRetentionDays = 30
  }

  fcm {
    enabled = false
    credentialsFile = ""
  }
}
